github-repo: "https://github.com/spring-io/gradle-enterprise-conventions.git"
github-repo-name: "spring-io/gradle-enterprise-conventions"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
build-name: "gradle-enterprise-conventions"
bintray-subject: "spring"
bintray-repo: "jars"